### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by thany** [mariusGundersen/gulp-amd-optimizer#9]
Getting this when trying to use this module:
```
TypeError: Cannot use 'in' operator to search for 'baseUrl' in js/main
    at module.exports (D:\Klanten\qsdashboard\node_modules\gulp-amd-optimizer\index.js:28:42)
    at Gulp.<anonymous> (D:\Klanten\qsdashboard\Gulpfile.js:112:13)
    at module.exports (D:\Klanten\qsdashboard\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Klanten\qsdashboard\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Klanten\qsdashboard\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Klanten\qsdashboard\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Martijn\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
```
Apparently, it's not/no longer allowed to use the `in` operator.

Everything is latest up-to-date.

**Comment by mariusGundersen** [comment]
did you pass in an object as the first parameter? 

```
gulp.src('*.js')
.pipe(optimize({}))
//....
```

**Comment by thany** [comment]
Yes, my config object. I've already moved to a different optimizer, but I do remember having to set baseUrl to undefined in order for requirejs's "funky" (to put it lightly) path handling to work properly.

Either way, if you're doing any operation on a (for you) unknown value, you should check it first. Then, you can report back to the console what's actually wrong, rather than letting it fail like this. Easy to forget, I'll admit ;)

**Comment by mariusGundersen** [comment]
Yes, the input validation could be better, I agree :)
